version: '3.3'
services:
  api:
    build: docker
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    environment:
      MYSQL_DSN: 'host=db;dbname=bookstore;charset=utf8mb4'
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: bookstore
    ports:
      - 8200:80
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-volume:/var/lib/mysql
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute "SHOW DATABASES;"
      retries: 20
      interval: 2s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8201:80

volumes:
  db-volume:
